In [2]:
# Importiamo tutti i file

import pandas as pd

aisles=pd.read_csv("aisles.csv")
departments=pd.read_csv("departments.csv")
order_prior=pd.read_csv("order_prior.csv")
order_train=pd.read_csv("order_train.csv")
orders=pd.read_csv("orders.csv")
products=pd.read_csv("products.csv")

In [3]:
#Verifico quante righe e colonne ci sono
aisles.shape

(134, 2)

In [4]:
#verifico il tipo di dato delle colonne
aisles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   aisle_id  134 non-null    int64
 1   aisle     134 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.2+ KB

In [5]:
#Verifico le prime 5 e le ultime 5 righe
display(aisles.head(5))
display(aisles.tail(5))

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

     aisle_id                       aisle
129       130    hot cereal pancake mixes
130       131                   dry pasta
131       132                      beauty
132       133  muscles joints pain relief
133       134  specialty wines champagnes

In [6]:
#Vediamo se ci sono duplicati
aisles.duplicated().sum()
aisles["aisle_id"].duplicated().sum()

np.int64(0)

In [7]:
#Vediamo se ci sono i null
aisles.isna().sum()

aisle_id    0
aisle       0
dtype: int64

In [8]:
#tagliamo gli spazi prima e dopo e i valori in minuscolo
aisles['aisle'] = aisles['aisle'].str.lower().str.strip()

In [9]:
#Rendiamo il titolo più leggibile per power bi
aisles['aisle'] = aisles['aisle'].str.title()

aisles

     aisle_id                       aisle
0           1       Prepared Soups Salads
1           2           Specialty Cheeses
2           3         Energy Granola Bars
3           4               Instant Foods
4           5  Marinades Meat Preparation
..        ...                         ...
129       130    Hot Cereal Pancake Mixes
130       131                   Dry Pasta
131       132                      Beauty
132       133  Muscles Joints Pain Relief
133       134  Specialty Wines Champagnes

[134 rows x 2 columns]

In [10]:
departments.shape

(21, 2)

In [11]:
departments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     object
dtypes: int64(1), object(1)
memory usage: 468.0+ bytes

In [12]:
departments.head(5)
departments.tail(5)

    department_id department
16             17  household
17             18     babies
18             19     snacks
19             20       deli
20             21    missing

In [13]:
departments.duplicated().sum()
departments["department_id"].duplicated().sum()

np.int64(0)

In [14]:
departments.isna().sum()

department_id    0
department       0
dtype: int64

In [15]:
departments['department'] = departments['department'].str.lower().str.strip()
departments['department'] = departments['department'].str.title()

departments

    department_id       department
0               1           Frozen
1               2            Other
2               3           Bakery
3               4          Produce
4               5          Alcohol
5               6    International
6               7        Beverages
7               8             Pets
8               9  Dry Goods Pasta
9              10             Bulk
10             11    Personal Care
11             12     Meat Seafood
12             13           Pantry
13             14        Breakfast
14             15     Canned Goods
15             16       Dairy Eggs
16             17        Household
17             18           Babies
18             19           Snacks
19             20             Deli
20             21          Missing

In [16]:
order_prior.shape
order_prior.info()
order_prior.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32434489 entries, 0 to 32434488
Data columns (total 4 columns):
 #   Column             Dtype
---  ------             -----
 0   order_id           int64
 1   product_id         int64
 2   add_to_cart_order  int64
 3   reordered          int64
dtypes: int64(4)
memory usage: 989.8 MB

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [17]:
order_prior.head(5)

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [18]:
#Controllo se lo stesso periodo è stato inserito due volte nello stesso ordine
order_prior.duplicated(subset=['order_id','product_id']).sum()

np.int64(0)

In [19]:
#verifichiamo se ci sono valori anomali
print(order_prior['reordered'].value_counts())
order_prior['add_to_cart_order'].describe()

reordered
1    19126536
0    13307953
Name: count, dtype: int64

count    3.243449e+07
mean     8.351076e+00
std      7.126671e+00
min      1.000000e+00
25%      3.000000e+00
50%      6.000000e+00
75%      1.100000e+01
max      1.450000e+02
Name: add_to_cart_order, dtype: float64

In [20]:
order_prior['order_id'] = order_prior['order_id'].astype('int32')
order_prior['product_id'] = order_prior['product_id'].astype('int32')
order_prior['add_to_cart_order'] = order_prior['add_to_cart_order'].astype('int16')
order_prior['reordered'] = order_prior['reordered'].astype('int8')

In [21]:
order_train.shape
order_train.info()
order_train.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1384617 entries, 0 to 1384616
Data columns (total 4 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   order_id           1384617 non-null  int64
 1   product_id         1384617 non-null  int64
 2   add_to_cart_order  1384617 non-null  int64
 3   reordered          1384617 non-null  int64
dtypes: int64(4)
memory usage: 42.3 MB

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [22]:
order_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [23]:
order_train.duplicated(subset=['order_id','product_id']).sum()

np.int64(0)

In [24]:
print(order_train['reordered'].value_counts())
order_train['add_to_cart_order'].describe()

reordered
1    828824
0    555793
Name: count, dtype: int64

count    1.384617e+06
mean     8.758044e+00
std      7.423936e+00
min      1.000000e+00
25%      3.000000e+00
50%      7.000000e+00
75%      1.200000e+01
max      8.000000e+01
Name: add_to_cart_order, dtype: float64

In [25]:
order_train['order_id'] = order_train['order_id'].astype('int32')
order_train['product_id'] = order_train['product_id'].astype('int32')
order_train['add_to_cart_order'] = order_train['add_to_cart_order'].astype('int16')
order_train['reordered'] = order_train['reordered'].astype('int8')

In [26]:
orders.info()
orders.describe()
orders.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                object
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), object(1)
memory usage: 182.7+ MB

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [27]:
display(orders.head())
display(orders.tail())

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [28]:
#Andiamo a filtrare solo su prior per lavorare su movimenti storici, quindi train(usato per ML) e test li andiamo a filtrare
orders = orders[orders['eval_set'] == 'prior']

In [29]:
orders.shape

(3214874, 7)

In [33]:
orders["order_dow"]=orders["order_dow"].replace(0,7)

In [35]:
#creiamo una nuova colonna per i giorni della settimana
days_map = {
    1: 'Monday',
    2: 'Tuesday',
    3: 'Wednesday',
    4: 'Thursday',
    5: 'Friday',
    6: 'Saturday',
    7: 'Sunday',
}

orders['order_day_name'] = orders['order_dow'].map(days_map)

In [ ]:
#deve essere da 0 a 6
orders['order_dow'].unique()

array([2, 3, 4, 1, 5, 0, 6])

In [ ]:
#Deve essere tra 0 a 23
orders["order_hour_of_day"].unique()

array([ 8,  7, 12, 15,  9, 14, 16, 11, 10, 19, 18, 17, 13, 20,  0, 21, 22,
        5, 23,  4,  6,  1,  2,  3])

In [ ]:
# i null non preoccupano perchè corrispondono ai primi ordini
orders['days_since_prior_order'].isnull().sum()

np.int64(206209)

In [ ]:
#al posto dei null mettiamo 0
orders['days_since_prior_order'] = orders['days_since_prior_order'].fillna(0)

In [ ]:
orders.dtypes

order_id                   int32
user_id                    int32
eval_set                  object
order_number               int16
order_dow                   int8
order_hour_of_day           int8
days_since_prior_order     int16
order_day_name            object
dtype: object

In [ ]:
#ottimizziamo la memoria
orders['order_id'] = orders['order_id'].astype('int32')
orders['user_id'] = orders['user_id'].astype('int32')
orders['order_number'] = orders['order_number'].astype('int16')
orders['order_dow'] = orders['order_dow'].astype('int8')
orders['order_hour_of_day'] = orders['order_hour_of_day'].astype('int8')
orders['days_since_prior_order'] = orders['days_since_prior_order'].astype('int16')

In [ ]:
products.shape
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49688 entries, 0 to 49687
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49688 non-null  int64
 1   product_name   49688 non-null  object
 2   aisle_id       49688 non-null  int64
 3   department_id  49688 non-null  int64
dtypes: int64(3), object(1)
memory usage: 1.5+ MB

In [ ]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [ ]:
products.isnull().sum()

product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64

In [ ]:
print(products['product_id'].duplicated().sum())

0

In [ ]:
products['product_name'] = products['product_name'].str.lower().str.strip()

In [ ]:
products.dtypes

product_id        int32
product_name     object
aisle_id          int16
department_id     int16
dtype: object

In [ ]:
products['product_id'] = products['product_id'].astype('int32')
products['aisle_id'] = products['aisle_id'].astype('int16')
products['department_id'] = products['department_id'].astype('int16')

In [36]:
orders.to_csv("clean_orders.csv",index=False)

In [ ]:
# import pandas as pd
# from sqlalchemy import create_engine
# import sqlalchemy

# # -------------------------------
# # Configurazione connessione SQL
# # -------------------------------
# # Sostituisci 'tuo_utente' e 'tua_password' con quelli reali
# engine = create_engine("mysql+pymysql://root:211100@localhost/instacart")

# # -------------------------------
# # Percorso cartella Capstone Project
# # -------------------------------
# folder = "C:/Users/Utente/OneDrive/Desktop/Capstone Project/"

# # -------------------------------
# # Lista CSV e tabelle corrispondenti
# # -------------------------------
# files_tables = [
#     ("clean_orders.csv", "orders"),
#     ("clean_order_prior.csv", "order_prior"),
#     ("clean_order_train.csv", "order_train"),
#     ("clean_products.csv", "products"),
#     ("clean_aisles.csv", "aisles"),
#     ("clean_departments.csv", "departments")
# ]

# # -------------------------------
# # Funzione per caricare CSV grandi a chunk
# # -------------------------------
# def load_csv_in_chunks(file_path, table_name, chunksize=50000, dtype=None):
#     print(f"⏳ Caricamento {table_name} in corso...")
#     for i, chunk in enumerate(pd.read_csv(file_path, chunksize=chunksize)):
#         chunk.to_sql(table_name, con=engine, if_exists='append', index=False, dtype=dtype)
#         print(f"    → Chunk {i+1} caricato ({len(chunk)} righe)")
#     print(f"✅ {table_name} caricata completamente!\n")

# # -------------------------------
# # Caricamento dei CSV
# # -------------------------------

# # Carica prima i file piccoli senza chunk
# load_csv_in_chunks(folder + "clean_aisles.csv", "aisles", chunksize=1000)
# load_csv_in_chunks(folder + "clean_departments.csv", "departments", chunksize=1000)

# # Carica products specificando VARCHAR più lungo per product_name
# load_csv_in_chunks(
#     folder + "clean_products.csv", 
#     "products", 
#     chunksize=10000, 
#     dtype={"product_name": sqlalchemy.types.VARCHAR(500)}
# )

# # Carica i file grandi a chunk
# load_csv_in_chunks(folder + "clean_orders.csv", "orders", chunksize=50000)
# load_csv_in_chunks(folder + "clean_order_prior.csv", "order_prior", chunksize=50000)
# load_csv_in_chunks(folder + "clean_order_train.csv", "order_train", chunksize=50000)

# print("🎉 Tutti i file della cartella Capstone Project sono stati caricati in SQL correttamente!")

⏳ Caricamento aisles in corso...

IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '1' for key 'aisles.PRIMARY'")
[SQL: INSERT INTO aisles (aisle_id, aisle) VALUES (%(aisle_id)s, %(aisle)s)]
[parameters: [{'aisle_id': 1, 'aisle': 'Prepared Soups Salads'}, {'aisle_id': 2, 'aisle': 'Specialty Cheeses'}, {'aisle_id': 3, 'aisle': 'Energy Granola Bars'}, {'aisle_id': 4, 'aisle': 'Instant Foods'}, {'aisle_id': 5, 'aisle': 'Marinades Meat Preparation'}, {'aisle_id': 6, 'aisle': 'Other'}, {'aisle_id': 7, 'aisle': 'Packaged Meat'}, {'aisle_id': 8, 'aisle': 'Bakery Desserts'}  ... displaying 10 of 134 total bound parameter sets ...  {'aisle_id': 133, 'aisle': 'Muscles Joints Pain Relief'}, {'aisle_id': 134, 'aisle': 'Specialty Wines Champagnes'}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)